import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{createClient,type User}from"@supabase/supabase-js";
import{Bell,Bookmark,BriefcaseBusiness,ChevronRight,Compass,Heart,Home,LogOut,Menu,MessageCircle,Plus,Search,Send,Settings,UserRound,Users,Image as ImageIcon,X}from"lucide-react";
import"./styles.css";

const URL=import.meta.env.VITE_SUPABASE_URL||"",KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||"";
const sb=URL&&KEY?createClient(URL,KEY):null;
type Screen="home"|"discover"|"create"|"opportunities"|"profile"|"messages"|"notifications"|"settings"|"project";
const projects=[
{id:"d1",title:"Restaurant Brand Identity",creator:"Amina Yusuf",profession:"Graphic Designer",category:"Design",description:"A complete visual identity built for a modern Lagos restaurant.",skills:["Branding","Graphic Design"],likes:42,comments:8},
{id:"d2",title:"E-commerce Mobile Experience",creator:"Daniel Okafor",profession:"Product Designer",category:"Design",description:"A mobile-first shopping experience focused on clarity and conversion.",skills:["UI/UX","Figma"],likes:31,comments:5},
{id:"d3",title:"Afrobeats Visual Campaign",creator:"Tobi Ade",profession:"Creative Director",category:"Creative",description:"Campaign visuals created for an independent music release.",skills:["Art Direction","Creative"],likes:57,comments:11}
];
const opps=[
{id:"o1",title:"Need a graphic designer for restaurant branding",creator:"Kola Ventures",skills:["Branding","Graphic Design"],location:"Lagos / Remote",budget:"₦150k–₦250k"},
{id:"o2",title:"Frontend developer for MVP build",creator:"Startup Team",skills:["React","TypeScript"],location:"Remote",budget:"₦300k–₦500k"}
];

function App(){
 const[user,setUser]=useState<User|null>(null),[screen,setScreen]=useState<Screen>("home"),[selected,setSelected]=useState<any>(),[q,setQ]=useState(""),[toast,setToast]=useState(""),[menu,setMenu]=useState(false);
 useEffect(()=>{if(!sb)return;sb.auth.getSession().then(({data})=>setUser(data.session?.user??null));const{x}=sb.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>x.subscription.unsubscribe()},[]);
 const note=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2400)},go=(x:Screen)=>{setScreen(x);setMenu(false)};
 if(!user)return <Auth onUser={setUser} note={note}/>;
 return <div className="app">
  <header><button className="brand" onClick={()=>go("home")}><b>B</b> Builder</button><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&go("discover")} placeholder="Search Builders, skills or projects"/></div><div className="actions"><button onClick={()=>go("notifications")}><Bell/></button><button onClick={()=>go("messages")}><MessageCircle/></button><button className="avatar" onClick={()=>go("profile")}>{(user.email?.[0]||"B").toUpperCase()}</button><button className="hamb" onClick={()=>setMenu(!menu)}><Menu/></button></div></header>
  {menu&&<div className="mobileMenu"><button onClick={()=>go("profile")}><UserRound/>Profile</button><button onClick={()=>go("settings")}><Settings/>Settings</button><button onClick={async()=>{await sb?.auth.signOut();note("Signed out")}}><LogOut/>Log out</button></div>}
  <main><aside><Nav i={<Home/>} t="Home" a={screen==="home"} f={()=>go("home")}/><Nav i={<Compass/>} t="Discover" a={screen==="discover"} f={()=>go("discover")}/><button className="create" onClick={()=>go("create")}><Plus/>Create</button><Nav i={<BriefcaseBusiness/>} t="Opportunities" a={screen==="opportunities"} f={()=>go("opportunities")}/><Nav i={<UserRound/>} t="Profile" a={screen==="profile"} f={()=>go("profile")}/><div className="push"><Nav i={<MessageCircle/>} t="Messages" a={screen==="messages"} f={()=>go("messages")}/><Nav i={<Settings/>} t="Settings" a={screen==="settings"} f={()=>go("settings")}/></div></aside>
  <section className="content">
   {screen==="home"&&<Home onOpen={(p:any)=>{setSelected(p);go("project")}} note={note}/>}
   {screen==="discover"&&<Discover q={q} onOpen={(p:any)=>{setSelected(p);go("project")}}/>}
   {screen==="create"&&<Create note={note} done={()=>go("profile")}/>}
   {screen==="opportunities"&&<Opportunities note={note}/>}
   {screen==="profile"&&<Profile user={user} note={note}/>}
   {screen==="project"&&<Detail p={selected} note={note}/>}
   {screen==="messages"&&<Messages note={note}/>}
   {screen==="notifications"&&<Notifications/>}
   {screen==="settings"&&<SettingsPage user={user} note={note}/>}
  </section></main>
  <nav className="bottom"><Nav i={<Home/>} t="Home" a={screen==="home"} f={()=>go("home")}/><Nav i={<Compass/>} t="Discover" a={screen==="discover"} f={()=>go("discover")}/><button onClick={()=>go("create")}><Plus/></button><Nav i={<BriefcaseBusiness/>} t="Jobs" a={screen==="opportunities"} f={()=>go("opportunities")}/><Nav i={<UserRound/>} t="Profile" a={screen==="profile"} f={()=>go("profile")}/></nav>
  {toast&&<div className="toast">{toast}</div>}
 </div>
}
function Auth({onUser,note}:{onUser:(u:User)=>void,note:(s:string)=>void}){
 const[mode,setMode]=useState<"signup"|"login">("signup"),[name,setName]=useState(""),[email,setEmail]=useState(""),[pass,setPass]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setErr("");if(!sb){setErr("Connect Supabase with your .env values first.");return}setBusy(true);const r=mode==="signup"?await sb.auth.signUp({email,password:pass,options:{data:{full_name:name}}}):await sb.auth.signInWithPassword({email,password:pass});setBusy(false);if(r.error){setErr(r.error.message);return}if(r.data.user)onUser(r.data.user);note("Welcome to Builder.");}
 return <div className="auth"><div className="pitch"><strong>B</strong><small>BUILDER</small><h1>Your work.<br/>Your proof.<br/>Your reputation.</h1><p>Build a professional identity around what you can actually do.</p></div><div className="authbox"><div className="authbrand"><b>B</b> Builder</div><h2>{mode==="signup"?"Create your Builder profile":"Welcome back"}</h2><p>Show people what you can actually do.</p><form onSubmit={submit}>{mode==="signup"&&<label>Full name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input required minLength={6} type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="At least 6 characters"/></label>{err&&<div className="error">{err}</div>}<button className="primary" disabled={busy}>{busy?"Please wait…":mode==="signup"?"Create account":"Log in"}</button></form><button className="switch" onClick={()=>setMode(mode==="signup"?"login":"signup")}>{mode==="signup"?"Already have an account? Log in":"New to Builder? Create an account"}</button></div></div>
}
function Nav({i,t,a,f}:any){return <button className={"nav "+(a?"active":"")} onClick={f}>{React.cloneElement(i,{size:19})}<span>{t}</span></button>}
function Head({eyebrow,title,sub,button}:{eyebrow:string,title:string,sub?:string,button?:React.ReactNode}){return <div className="head"><div><small>{eyebrow}</small><h1>{title}</h1>{sub&&<p>{sub}</p>}</div>{button}</div>}
function Home({onOpen,note}:{onOpen:(p:any)=>void,note:(s:string)=>void}){return <><Head eyebrow="DISCOVER WORK" title="What are Builders creating?" sub="Proof beats promises." button={<button className="primary" onClick={()=>note("Use Create to publish a project.")}><Plus/>Add project</button>}/><div className="feed">{projects.map(p=><Card key={p.id} p={p} open={()=>onOpen(p)} note={note}/>)}</div></>}
function Card({p,open,note}:{p:any,open:()=>void,note:(s:string)=>void}){const[liked,setLiked]=useState(false),[saved,setSaved]=useState(false);return <article className="card"><div className="person"><div className="avatar">{p.creator[0]}</div><div><b>{p.creator}</b><span>{p.profession}</span></div></div><div className="media"><ImageIcon/><span>{p.category}</span></div><div className="body"><h3>{p.title}</h3><p>{p.description}</p><div className="chips">{p.skills.map((s:string)=><span key={s}>{s}</span>)}</div></div><div className="cardactions"><button className={liked?"liked":""} onClick={()=>{setLiked(!liked);note(liked?"Removed like":"Project liked")}}><Heart fill={liked?"currentColor":"none"}/> {p.likes}</button><button onClick={()=>note("Comments opened.")}><MessageCircle/> {p.comments}</button><button className={saved?"saved":""} onClick={()=>{setSaved(!saved);note(saved?"Removed from saves":"Saved")}}><Bookmark fill={saved?"currentColor":"none"}/></button><button className="view" onClick={open}>View project <ChevronRight/></button></div></article>}
function Discover({q,onOpen}:{q:string,onOpen:(p:any)=>void}){const list=projects.filter(p=>(p.title+" "+p.creator+" "+p.profession+" "+p.skills.join(" ")).toLowerCase().includes(q.toLowerCase()));return <><Head eyebrow="DISCOVER" title="Find people who can do the work."/><div className="largeSearch"><Search/><input placeholder="Search Builders, projects, skills or locations" defaultValue={q}/></div><h2 className="count">{list.length} results</h2><div className="feed">{list.map(p=><Card key={p.id} p={p} open={()=>onOpen(p)} note={()=>{}}/>)}</div></>}
function Create({note,done}:{note:(s:string)=>void,done:()=>void}){const[kind,setKind]=useState<"project"|"opportunity">("project"),[title,setTitle]=useState(""),[desc,setDesc]=useState(""),[cat,setCat]=useState("Design"),[busy,setBusy]=useState(false);async function save(){if(!title||!desc)return note("Title and description are required.");if(!sb)return note("Supabase is not connected.");const{data:{user}}=await sb.auth.getUser();if(!user)return note("Please log in.");setBusy(true);const table=kind==="project"?"projects":"opportunities",payload=kind==="project"?{user_id:user.id,title,description:desc,category:cat,status:"completed"}:{user_id:user.id,title,description:desc,required_skills:cat,status:"open"};const{error}=await sb.from(table).insert(payload);setBusy(false);if(error)return note(error.message);note("Published successfully.");done()}return <div className="formpage"><Head eyebrow="CREATE" title="Put proof into the world."/><div className="tabs"><button className={kind==="project"?"sel":""} onClick={()=>setKind("project")}>Publish Project</button><button className={kind==="opportunity"?"sel":""} onClick={()=>setKind("opportunity")}>Post Opportunity</button></div><div className="form"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give it a clear title"/></label><label>Description<textarea rows={6} value={desc} onChange={e=>setDesc(e.target.value)} placeholder="Explain the work clearly."/></label><label>{kind==="project"?"Category":"Required skills"}<input value={cat} onChange={e=>setCat(e.target.value)}/></label><button className="primary" disabled={busy} onClick={save}>{busy?"Publishing…":"Publish"}</button></div></div>}
function Opportunities({note}:{note:(s:string)=>void}){return <><Head eyebrow="OPPORTUNITIES" title="Work worth finding." sub="Connect real skills to real opportunities."/><div className="oppgrid">{opps.map(o=><article className="opp" key={o.id}><small>OPEN</small><h2>{o.title}</h2><p>{o.creator}</p><div className="chips">{o.skills.map(s=><span key={s}>{s}</span>)}</div><hr/><div className="meta"><span>{o.location}</span><b>{o.budget}</b></div><button className="secondary" onClick={()=>note("Application flow opened.")}>View & apply</button></article>)}</div></>}
function Profile({user,note}:{user:User,note:(s:string)=>void}){const[p,setP]=useState<any>(null);useEffect(()=>{sb?.from("profiles").select("*").eq("user_id",user.id).single().then(({data})=>setP(data))},[user.id]);const name=p?.full_name||user.user_metadata?.full_name||"Your Builder profile";return <><div className="profile"><div className="avatar huge">{name[0]}</div><div><small>BUILDER PROFILE</small><h1>{name}</h1><p>{p?.profession||"Add your profession"} · {p?.location||"Add your location"}</p><p>{p?.bio||"Show the world what you can actually do."}</p><button className="secondary" onClick={()=>note("Profile editor will be wired next.")}>Edit profile</button></div></div><div className="stats"><div><b>0</b><span>Projects</span></div><div><b>0</b><span>Followers</span></div><div><b>0</b><span>Following</span></div><div><b>0</b><span>Reviews</span></div></div><div className="empty"><BriefcaseBusiness/><h2>Your proof starts here.</h2><p>Publish your first genuine project.</p></div></>}
function Detail({p,note}:{p:any,note:(s:string)=>void}){if(!p)return <div className="empty">No project selected.</div>;return <><button className="back" onClick={()=>history.back()}>← Back</button><div className="detailmedia"><ImageIcon/></div><div className="detail"><small>{p.category}</small><h1>{p.title}</h1><p>{p.creator} · {p.profession}</p><div className="chips">{p.skills.map((s:string)=><span key={s}>{s}</span>)}</div><p className="detailtext">{p.description}</p><button className="primary" onClick={()=>note("Contact flow opened.")}><MessageCircle/>Contact Builder</button></div></>}
function Messages({note}:{note:(s:string)=>void}){const[m,setM]=useState("");return <><Head eyebrow="MESSAGES" title="Conversations"/><div className="messages"><aside><div className="conversation active"><div className="avatar">A</div><div><b>Amina Yusuf</b><span>Can you send the project details?</span></div></div><div className="conversation"><div className="avatar">D</div><div><b>Daniel Okafor</b><span>Thanks for reaching out.</span></div></div></aside><section><div className="chathead"><div className="avatar">A</div><b>Amina Yusuf</b></div><div className="chat"><div className="bubble">Hi! I saw your Builder profile.</div><div className="bubble mine">Thanks — happy to connect.</div></div><form onSubmit={e=>{e.preventDefault();if(m){note("Message sent.");setM("")}}}><input value={m} onChange={e=>setM(e.target.value)} placeholder="Write a message…"/><button><Send/></button></form></section></div></>}
function Notifications(){return <><Head eyebrow="NOTIFICATIONS" title="Activity"/><div className="notifs"><div><Heart/><p><b>Amina Yusuf</b> liked your project.</p><span>2m</span></div><div><Users/><p><b>Daniel Okafor</b> followed you.</p><span>1h</span></div><div><BriefcaseBusiness/><p>You received a new opportunity.</p><span>3h</span></div></div></>}
function SettingsPage({user,note}:{user:User,note:(s:string)=>void}){return <><Head eyebrow="SETTINGS" title="Account & privacy"/><div className="settings">{["Edit profile","Notifications","Privacy","Change password"].map(x=><button key={x} onClick={()=>note(x+" settings opened.")}><Settings/>{x}<ChevronRight/></button>)}<button onClick={async()=>{await sb?.auth.signOut();note("Logged out.")}}><LogOut/>Log out<ChevronRight/></button><button className="danger"><X/>Delete account<ChevronRight/></button></div><p>{user.email}</p></>}
createRoot(document.getElementById("root")!).render(<App/>);
